target 'ChatKit-OC' do
  platform :ios , '8.0'
  inhibit_all_warnings!

  #=========================================================
  #======================== Lib Dependency =================
  #=========================================================

  #=========================================================
  #======================== Demo Dependency ================
  #=========================================================

  pod 'CYLTabBarController', '1.9.0'
  pod 'TWMessageBarManager', '1.8.1'
  pod 'MLPAutoCompleteTextField', '1.5'
  pod 'FTPopOverMenu', '1.3.2'
  pod 'RedpacketLib' ,'3.4.1'
  pod 'FXForms', '1.2.14'
  
  
  
  pod "AVOSCloud" , "~> 8.0.6"
  pod "AVOSCloudIM", "~> 8.0.6"
  pod "MJRefresh" , "~> 3.1.9"
  pod "Masonry" , "~> 1.0.1"
  pod "FMDB" , "~> 2.6.2"
  pod "pop", "~> 1.0.9"
  pod "UITableView+FDTemplateLayoutCell" , "~> 1.5.beta"
  pod "FDStackView" , "~> 1.0"
  pod "DACircularProgress" , "~> 2.3.1"
  pod "MLLabel" , "~> 1.9.2"
  pod "MWPhotoBrowser", "~> 2.1.2"
  pod "CYLDeallocBlockExecutor", "~> 1.1.2"
end
