# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

workspace 'LeanChat.xcworkspace'

target 'LeanChat' do
    xcodeproj 'LeanChat.xcodeproj'
    pod 'AVOSCloudIM'
    pod 'AVOSCloud'
    pod 'AVOSCloudCrashReporting'
    pod 'LeanChatLib' , :path => '../'
    pod 'MBProgressHUD', '0.9.1'
    pod 'AFNetworking', '2.5.4'
    pod 'LZAlertViewHelper' , '0.0.2'
    pod 'JSBadgeView', '1.4.1'
    pod 'LZMembersCell', '0.0.2'
    pod 'FXForms', '1.2.13'
    pod 'iVersion', '1.11.4'
    pod 'iRate', '1.11.4'
    pod 'LeanCloudFeedback'
    pod 'LeanCloudSocial', '0.0.7'
    pod 'OpenShare', '0.0.1'
    pod 'PopMenu', '2.4'
    pod 'CYLTabBarController'
    pod 'SDWebImage'
    pod 'BQMM', '1.7.10'

#    pod 'LeanCloudSocial', :path => '~/ios/leancloud-social-ios'
#    pod 'LeanCloudFeedback', :path => '~/ios/leancloud-feedback-ios/'
    end

# ENV["COCOAPODS_DISABLE_STATS"] = "true"
